import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import DefaultLayout from "./layouts/defaultLayout";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: [
    "100",
    "400",
    "600"
  ],
});



export const metadata: Metadata = {
  title: "Pokedex App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased h-svh`}
      >
        <Suspense fallback={
          <DefaultLayout title="Pokedex">
            Loading ...
          </DefaultLayout>
        }>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
